### ISSUE TITLE
pass errors to the stream

### ISSUE THREAD

**Issue by chpio** [jeffbski/digest-stream#1]
hi,

i want to signal errors to the stream. eg:

``` javascript
digestStream('sha1', 'hex', (shasum, reject) => {
    if (dist.shasum !== shasum) {
        return reject(new Error(`shasum mismatch`));
    }
})
```

or by returning (could break some existing "returning" code)

``` javascript
digestStream('sha1', 'hex', shasum =>
    dist.shasum !== shasum ? new Error(`shasum mismatch`) : undefined
)
```

**Comment by jeffbski** [comment]
I have published v1.0.1 which allows you to return an instance of Error (or anything inheriting from Error) from your listenerFn. Anything returned other than errors will be ignored.

``` javascript
digestStream('sha1', 'hex', shasum =>
    dist.shasum !== shasum ? new Error(`shasum mismatch`) : undefined
)
```

https://github.com/jeffbski/digest-stream/commit/83d0bc6141dd1541eab899f14a1f0effd528be86

**Comment by chpio** [comment]
wow, that was fast, thank you!

**Comment by jeffbski** [comment]
You are welcome! Fortunately it was an easy thing to add and test.

On Fri, Feb 26, 2016 at 12:44 PM, chpio notifications@github.com wrote:

> wow, that was fast, thank you!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jeffbski/digest-stream/issues/1#issuecomment-189419405
> .

## 

Jeff Barczewski
Founder of CodeWinds
http://codewinds.com/
Web developer training - screencasts, podcast, blog
